workspace/view/member/urls.py
from django.urls import path
from django.views.generic import TemplateView

from member.views import MemberJoinView, MemberLoginView, MemberLogoutView

app_name = 'member'



urlpatterns = [
    # path('join/', TemplateView.as_view(template_name='member/join.html'))
    path('join/', MemberJoinView.as_view(), name='join'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('logout/', MemberLogoutView.as_view(), name='logout'),
    path('success/', TemplateView.as_view(template_name='member/success.html'), name='success'),
    path('fail/', TemplateView.as_view(template_name='member/fail.html'), name='fail'),
]

workspace/view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostListView, PostDeleteView

app_name = 'post'

urlpatterns = [
    # path('list/<int:page>/<int:size>/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListView.as_view(), name='list'),
    path('list/', PostListView.as_view(), name='list_init'),
    path('write/<int:page>/', PostWriteView.as_view(), name='write'),
    path('detail/<int:post_id>/<int:page>/', PostDetailView.as_view(), name='detail'),
    path('update/<int:post_id>/<int:page>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:post_id>/', PostDeleteView.as_view(), name='delete')
]

workspace/view/view/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # member로 시작되는 URL은 member app에 있는 urls.py로 가라!
    path('member/', include('member.urls')),
    # post로 시작되는 URL은 post app에 있는 urls.py로 가라!
    path('post/', include('post.urls')),
    path('replies/', include('reply.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workspace/view/post/models.py
from django.db import models

from member.models import Member
from view.models import Period


# Create your models here.
class Post(Period):
    post_title = models.CharField(max_length=200, null=False, blank=True)
    post_content = models.CharField(max_length=500, null=False, blank=True)
    member = models.ForeignKey(Member, null=False, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']
        db_table = 'tbl_post'

    def get_absolute_url(self, page):
        return f"/post/detail/{self.id}/{page}"


class PostFile(Period):
    post = models.ForeignKey(Post, null=False, on_delete=models.CASCADE)
    image = models.ImageField(null=False, blank=False, upload_to='post/%Y/%m/%d')

    class Meta:
        db_table = 'tbl_post_file'

workspace/view/post/views.py
import math

from django.conf import settings
from django.shortcuts import render, redirect
from django.views import View

from member.models import Member
from post.models import Post, PostFile


# Create your views here.

# 게시글 목록
class PostListView(View):
    def get(self, request, page=1):
        size = 5
        offset = (page - 1) * size
        limit = page * size
        total = Post.objects.all().count()
        pageCount = 5
        endPage = math.ceil(page / pageCount) * pageCount
        startPage = endPage - pageCount + 1
        realEnd = math.ceil(total / size)
        endPage = realEnd if endPage > realEnd else endPage
        pageUnit = (page - 1 // 5) + 1
        if endPage == 0:
            endPage = 1

        context = {
            'posts': list(Post.objects.all())[offset:limit],
            'startPage': startPage,
            'endPage': endPage,
            'page': page,
            'realEnd': realEnd,
            'member_name': Member.objects.get(member_email=request.session['member_email']).member_name,
        }
        return render(request, 'post/list.html', context)


# 게시글 작성
class PostWriteView(View):
    def get(self, request, page):
        return render(request, "post/write.html", {'member_name': Member.objects.get(member_email=request.session['member_email']).member_name, 'page': page})

    def post(self, request, page=1):
        datas = request.POST
        files = request.FILES

        datas = {
            'member_id': Member.objects.get(member_email=request.session['member_email']).id,
            'post_title': datas['post_title'],
            'post_content': datas['post_content']
        }

        post = Post.objects.create(**datas)
        # 태그 한 개 multiple
        for file in files.getlist('file1'):
            PostFile.objects.create(post=post, image=file)

        # 태그 여러 개
        # for key in files:
        #     PostFile.objects.create(post=post, image=files[key])
        # PostFile.objects.create(post=post, image=files['file'])
        return redirect(post.get_absolute_url(page))


# 게시글 조회
class PostDetailView(View):
    def get(self, request, post_id, page):
        print(post_id)
        post = Post.objects.get(id=post_id)
        context = {
            'post': post,
            'post_files': list(post.postfile_set.all()),
            'page': page
        }
        return render(request, "post/detail.html", context)


# 게시글 수정
class PostUpdateView(View):
    def get(self, request, post_id, page):
        print(post_id)
        post = Post.objects.get(id=post_id)
        context = {'post': post, 'member_name': '한동석', 'page': page}
        # render(request, to, context): 바로 html 화면으로 이동
        return render(request, "post/update.html", context)

    def post(self, request, post_id, page):
        datas = request.POST
        datas = {
            'post_title': datas['post_title'],
            'post_content': datas['post_content']
        }
        Post.objects.filter(id=post_id).update(**datas)
        # redirect(to): URL로 이동하여 다른 View에서 render()로 html 화면 이동
        return redirect(Post.objects.get(id=post_id).get_absolute_url(page))


# 게시글 삭제
class PostDeleteView(View):
    def get(self, request, post_id):
        Post.objects.get(id=post_id).delete()
        return redirect('post:list_init')

workspace/view/templates/post/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>게시글 상세보기</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<a href="{% url 'post:list' page=page %}">목록 보기</a>
<a href="{% url 'post:write' page=page %}">글 작성하기</a>
<a href="{% url 'post:update' post_id=post.id page=page %}">글 수정하기</a>
<a href="{% url 'post:delete' post_id=post.id %}">글 삭제하기</a>
<table border="1">
    <tr>
        <th>제목</th>
        <th>내용</th>
        <th>작성자</th>
    </tr>
    <tr>
        <td>{{ post.post_title }}</td>
        <td>{{ post.post_content }}</td>
        <td>{{ post.member.member_name }}</td>
    </tr>
</table>
{% for post_file in post_files %}
    <img src="/upload/{{ post_file.image }}">
{% endfor %}
</body>
</html>

workspace/view/templates/post/list.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <a href="{% url 'post:write' page=page %}">글 작성하기</a>
    <title>게시글 목록</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style>
        ul {
            list-style: none;
            display: flex;
        }

        li {
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <h2>{{ member_name }}님 환영합니다! <a href="{% url 'member:logout' %}">로그아웃</a></h2>
    <table>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td><a  href="{% url 'post:detail' post_id=post.id page=page %}">{{ post.post_title }}</a></td>
                <td>{{ post.member.member_name }}</td>
            </tr>
        {% endfor %}
    </table>
    <ul>
    {% if startPage > 1 %}
        <a href="{% url 'post:list' page=startPage|add:-1 %}">이전</a>
    {% endif %}
    {% for i in "x"|rjust:5 %}
        {% if forloop.counter0|add:startPage <= realEnd%}
            <li>
                <a href="{% url 'post:list' page=forloop.counter0|add:startPage %}">{{ forloop.counter0|add:startPage}}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if endPage < realEnd %}
        <a href="{% url 'post:list' page=endPage|add:1 %}">다음</a>
    {% endif %}
    </ul>
</body>
</html>

workspace/view/templates/post/update.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>게시글 수정</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<form action="{% url 'post:update' post_id=post.id page=page %}" method="post">
    {% csrf_token %}
    <input type="text" value="{{ post.member.member_name }}" readonly>
    <input type="text" name="post_title" placeholder="게시글 제목" value="{{ post.post_title }}">
    <textarea name="post_content" cols="30" rows="10" placeholder="게시글 내용">{{ post.post_content }}</textarea>
    <input type="submit" value="완료">
</form>
</body>
</html>

workspace/view/templates/post/write.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>게시글 작성</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<a href="{% url 'post:list' page=page %}">목록 보기</a>
<form action="{% url 'post:write' page=1 %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" value="{{ member_name }}" readonly>
    <input type="text" name="post_title" placeholder="게시글 제목">
    <textarea name="post_content" cols="30" rows="10" placeholder="게시글 내용"></textarea>
    <div>
        <input type="file" name="file1" multiple>
{#        <input type="file" name="file2">#}
    </div>
    <input type="submit" value="완료">
</form>
</body>
</html>