workspace/view/member/urls.py
from django.urls import path
from django.views.generic import TemplateView

from member.views import MemberJoinView, MemberLoginView, MemberLogoutView

app_name = 'member'



urlpatterns = [
    # path('join/', TemplateView.as_view(template_name='member/join.html'))
    path('join/', MemberJoinView.as_view(), name='join'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('logout/', MemberLogoutView.as_view(), name='logout'),
    path('success/', TemplateView.as_view(template_name='member/success.html'), name='success'),
    path('fail/', TemplateView.as_view(template_name='member/fail.html'), name='fail'),
]

workspace/view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostListView, PostDeleteView

app_name = 'post'

urlpatterns = [
    # path('list/<int:page>/<int:size>/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListView.as_view(), name='list'),
    path('list/', PostListView.as_view(), name='list_init'),
    path('write/<int:page>/', PostWriteView.as_view(), name='write'),
    path('detail/<int:post_id>/<int:page>/', PostDetailView.as_view(), name='detail'),
    path('update/<int:post_id>/<int:page>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:post_id>/', PostDeleteView.as_view(), name='delete')
]

workspace/view/view/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    # member로 시작되는 URL은 member app에 있는 urls.py로 가라!
    path('member/', include('member.urls')),
    # post로 시작되는 URL은 post app에 있는 urls.py로 가라!
    path('post/', include('post.urls')),
    path('replies/', include('reply.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workspace/view/member/models.py
from django.db import models

from view.models import Period


# Create your models here.
class Member(Period):
    member_email = models.CharField(max_length=200, unique=True, null=False, blank=False)
    member_password = models.CharField(max_length=200, null=False, blank=False)
    member_name = models.CharField(max_length=200, null=False, blank=False)
    member_age = models.PositiveSmallIntegerField(default=0)
    member_birth = models.DateField(null=False, blank=False)

    class Meta:
        db_table = "tbl_member"

workspace/view/member/views.py
from django.shortcuts import render, redirect
from django.views import View

from member.models import Member


# Create your views here.
class MemberJoinView(View):

    def get(self, request, *args, **kwargs):
        # request와 실제 경로를 작성하여 이동한다.
        return render(request, 'member/join.html')

    def post(self, request, *args, **kwargs):
        token, member_email, member_password, member_name, member_age, member_birth = request.POST.values()
        Member.objects.create(member_email=member_email, member_password=member_password, member_name=member_name, member_age=member_age, member_birth=member_birth)
        # 이동할 urls 경로를 작성한다.
        return redirect('/member/login')
        # return redirect('member:login')


class MemberLoginView(View):
    def get(self, request):
        return render(request, 'member/login.html')

    def post(self, request):
        token, member_email, member_password = request.POST.values()
        if Member.objects.filter(member_email=member_email, member_password=member_password).exists():
            request.session['member_email'] = member_email
            return redirect('post:list_init')
            # return redirect('member:success')
        return redirect('member:login')
        # return redirect('member:fail')


class MemberLogoutView(View):
    def get(self, request):
        request.session.modified = True
        del request.session['member_email']
        print(request.session.get('member_email'))
        return redirect('member:login')

workspace/view/templates/member/fail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>실패</title>
</head>
    <h1>실패!</h1>
<body>

</body>
</html>

workspace/view/templates/member/join.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>회원가입</title>
</head>
<body>
<form action="{% url 'member:join' %}" method="post">
    {% csrf_token %}
    <input type="text" name="member_email" placeholder="아이디">
    <input type="password" name="member_password" placeholder="비밀번호">
    <input type="text" name="member_name" placeholder="이름">
    <input type="text" name="member_age" placeholder="나이">
    <input type="date" name="member_birth" placeholder="생년월일">
    <input type="submit" value="전송">
</form>
</body>
</html>

workspace/view/templates/member/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>로그인</title>
</head>
<body>
<form action="{% url 'member:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="member_email">
    <input type="password" name="member_password">
    <input type="submit" value="전송">
</form>
</body>
</html>

workspace/view/templates/member/success.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>성공</title>
</head>
<body>
    <h1>성공!</h1>
</body>
</html>